# Generated by Django 5.2.16 on 2026-07-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('years_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('condition_severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Critical', 'Critical')], max_length=20)),
                ('admission_type', models.CharField(choices=[('Planned', 'Planned'), ('Emergency', 'Emergency')], max_length=20)),
                ('outcome', models.CharField(choices=[('Cured', 'Cured'), ('Transferred', 'Transferred'), ('Deceased', 'Deceased')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('surgery_id', models.AutoField(primary_key=True, serialize=False)),
                ('surgery_date', models.DateField()),
                ('surgery_type', models.CharField(max_length=100)),
                ('outcome', models.CharField(choices=[('Success', 'Success'), ('Complication', 'Complication'), ('Death', 'Death')], max_length=20)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.admission')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.patient')),
            ],
        ),
    ]
